In [1]:
import pandas as pd
import numpy as np
import sklearn as skl
import matplotlib.pyplot as plt

c:\Users\Usuario\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [ ]:
# Tp3_tp4. Renombrar variables. Reemplazar datos ausentes. Crear nuevas variables. Crear variables categóricas mediante rangos.
# Normalizar variables numéricas. (Z-score, Min-Max). Copiar filas y modificar datos de una celda. 
# Usar expresiones regulares “regex” para modificar cadenas de caracteres. 
# Reemplazar datos nulos por indicadores estadísticos.

In [3]:
tabla3=pd.read_excel(r"C:\Users\Usuario\Documents\R Files\BBDD_Impo_SF.xlsx")
t3=pd.DataFrame(tabla3)
t3

,año,aduana,cod_iso_pais,pais,cod_sección,seccion,cod_capitulo,capitulo,Valor CIF (en Dólares),Peso Neto (en Kilos)
0,2018,Rosario,BRA,Brasil,I,Animales Vivos Y Productos Del Reino Animal,2.0,Carne y despojos comestibles,293473928,1136096851
1,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,7.0,"Hortalizas, plantas, raíces y tubérculos alime...",8580,546
2,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,8.0,Frutas y frutos comestibles; cortezas de agrio...,9774392,11340
3,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,9.0,"Café, te, yerba y especias",2318503402,101202382
4,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,12.0,"Semillas y frutos oleaginosos, semillas y frut...",1528837,1
...,...,...,...,...,...,...,...,...,...,...
2708,2016,Rafaela,NaN,Resto Países,XIII,"Manufacturas De Piedra, Yeso, Cemento, Ceramic...",70.0,Vidrio y sus manufacturas,1131,2
2709,2016,Rafaela,NaN,Resto Países,XV,Metales Comunes Y Sus Manufacturas,73.0,"Manufacturas de fundición, hierro o acero",36831,9053
2710,2016,Rafaela,NaN,Resto Países,XVI,"Maquinas, Aparatos Y Material Electrico; Sus P...",84.0,"Reactores nucleares, calderas, máquinas, apara...",985673,56274
2711,2016,Rafaela,NaN,Resto Países,XVI,"Maquinas, Aparatos Y Material Electrico; Sus P...",85.0,"Máquinas, aparatos y material eléctrico y sus ...",48557,319
2712,2016,Rafaela,NaN,Resto Países,XVIII,"Instrumentos De Optica, Medicina, Relojeria, M...",90.0,"Instrumentos y aparatos de óptica, de fotograf...",4313,3

In [4]:
print(t3.columns)

Index(['año', 'aduana', 'cod_iso_pais', 'pais', 'cod_sección', 'seccion',
       'cod_capitulo', 'capitulo', 'Valor CIF (en Dólares) ',
       'Peso Neto (en Kilos)'],
      dtype='object')

In [5]:
t3.pais.value_counts()

Resto Países                     442
China                            431
Brasil                           425
Estados Unidos                   326
Italia                           207
República Federal De Alemania    203
España                           161
México                            74
Chile                             71
Corea Republicana                 67
India                             49
Japón                             49
Paraguay                          45
Uruguay                           39
Polonia                           17
Taiwan                            17
Argentina                         14
Reino Unido                       11
Dinamarca                         11
Canadá                            10
Rusia                              8
Suiza                              6
Malasia                            6
Marruecos                          6
Turquía                            4
Venezuela                          3
Nigeria                            3
Perú                               2
Bolivia                            2
Arabia Saudita                     2
Países Bajos                       1
Trinidad Y Tobago                  1
Name: pais, dtype: int64

In [6]:
# Renombrar varaibles
#++++++++++++++++++++

t3.rename(columns={'Valor CIF (en Dólares) ':'Valor_CIF_USD'}, inplace=True)

t3.rename(columns={'Peso Neto (en Kilos)': 'Peso_Neto_KG'}, inplace=True)
t3

,año,aduana,cod_iso_pais,pais,cod_sección,seccion,cod_capitulo,capitulo,Valor_CIF_USD,Peso_Neto_KG
0,2018,Rosario,BRA,Brasil,I,Animales Vivos Y Productos Del Reino Animal,2.0,Carne y despojos comestibles,293473928,1136096851
1,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,7.0,"Hortalizas, plantas, raíces y tubérculos alime...",8580,546
2,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,8.0,Frutas y frutos comestibles; cortezas de agrio...,9774392,11340
3,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,9.0,"Café, te, yerba y especias",2318503402,101202382
4,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,12.0,"Semillas y frutos oleaginosos, semillas y frut...",1528837,1
...,...,...,...,...,...,...,...,...,...,...
2708,2016,Rafaela,NaN,Resto Países,XIII,"Manufacturas De Piedra, Yeso, Cemento, Ceramic...",70.0,Vidrio y sus manufacturas,1131,2
2709,2016,Rafaela,NaN,Resto Países,XV,Metales Comunes Y Sus Manufacturas,73.0,"Manufacturas de fundición, hierro o acero",36831,9053
2710,2016,Rafaela,NaN,Resto Países,XVI,"Maquinas, Aparatos Y Material Electrico; Sus P...",84.0,"Reactores nucleares, calderas, máquinas, apara...",985673,56274
2711,2016,Rafaela,NaN,Resto Países,XVI,"Maquinas, Aparatos Y Material Electrico; Sus P...",85.0,"Máquinas, aparatos y material eléctrico y sus ...",48557,319
2712,2016,Rafaela,NaN,Resto Países,XVIII,"Instrumentos De Optica, Medicina, Relojeria, M...",90.0,"Instrumentos y aparatos de óptica, de fotograf...",4313,3

In [7]:
#t3.columns = t3.columns.str.strip()

t3[['Valor_CIF_USD','Peso_Neto_KG']]

      Valor_CIF_USD  Peso_Neto_KG
0         293473928    1136096851
1              8580           546
2           9774392         11340
3        2318503402     101202382
4           1528837             1
...             ...           ...
2708           1131             2
2709          36831          9053
2710         985673         56274
2711          48557           319
2712           4313             3

[2713 rows x 2 columns]

In [8]:
t3.dtypes

año                int64
aduana            object
cod_iso_pais      object
pais              object
cod_sección       object
seccion           object
cod_capitulo     float64
capitulo          object
Valor_CIF_USD      int64
Peso_Neto_KG       int64
dtype: object

In [9]:
t3.shape

(2713, 10)

In [10]:
# Eliminar filas duplicadas
t3_np=t3.drop_duplicates(inplace=True) 
t3_np

In [11]:
# Datos ausentes en cada variable
t3.isna().sum().sort_values()

año                0
aduana             0
pais               0
cod_sección        0
seccion            0
capitulo           0
Valor_CIF_USD      0
Peso_Neto_KG       0
cod_capitulo       4
cod_iso_pais     442
dtype: int64

In [12]:
# Muestra las columnas seleccionadas del dataframe
t3[['cod_capitulo','cod_iso_pais']]

      cod_capitulo cod_iso_pais
0              2.0          BRA
1              7.0          BRA
2              8.0          BRA
3              9.0          BRA
4             12.0          BRA
...            ...          ...
2708          70.0          NaN
2709          73.0          NaN
2710          84.0          NaN
2711          85.0          NaN
2712          90.0          NaN

[2713 rows x 2 columns]

In [13]:
#Reemplazar datos ausentes
#+++++++++++++++++++++++++

# Asignar a  los datos nulos  de la var. "cod_iso_país" el prefijo "RP", el cual significa resto de paises
# # Asignar a  los datos nulos  de la var. "cod_capitulo" el mensaje ""falta_cod_cap".
t3.cod_iso_pais.replace({np.nan:"RP"},inplace=True)
t3.cod_capitulo.replace({np.nan:"falta_cod_cap"},inplace=True)
t3

,año,aduana,cod_iso_pais,pais,cod_sección,seccion,cod_capitulo,capitulo,Valor_CIF_USD,Peso_Neto_KG
0,2018,Rosario,BRA,Brasil,I,Animales Vivos Y Productos Del Reino Animal,2.0,Carne y despojos comestibles,293473928,1136096851
1,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,7.0,"Hortalizas, plantas, raíces y tubérculos alime...",8580,546
2,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,8.0,Frutas y frutos comestibles; cortezas de agrio...,9774392,11340
3,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,9.0,"Café, te, yerba y especias",2318503402,101202382
4,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,12.0,"Semillas y frutos oleaginosos, semillas y frut...",1528837,1
...,...,...,...,...,...,...,...,...,...,...
2708,2016,Rafaela,RP,Resto Países,XIII,"Manufacturas De Piedra, Yeso, Cemento, Ceramic...",70.0,Vidrio y sus manufacturas,1131,2
2709,2016,Rafaela,RP,Resto Países,XV,Metales Comunes Y Sus Manufacturas,73.0,"Manufacturas de fundición, hierro o acero",36831,9053
2710,2016,Rafaela,RP,Resto Países,XVI,"Maquinas, Aparatos Y Material Electrico; Sus P...",84.0,"Reactores nucleares, calderas, máquinas, apara...",985673,56274
2711,2016,Rafaela,RP,Resto Países,XVI,"Maquinas, Aparatos Y Material Electrico; Sus P...",85.0,"Máquinas, aparatos y material eléctrico y sus ...",48557,319
2712,2016,Rafaela,RP,Resto Países,XVIII,"Instrumentos De Optica, Medicina, Relojeria, M...",90.0,"Instrumentos y aparatos de óptica, de fotograf...",4313,3

In [14]:
# Cantidad de valores ausentes por atributo
t3.isna().sum().sort_values()

año              0
aduana           0
cod_iso_pais     0
pais             0
cod_sección      0
seccion          0
cod_capitulo     0
capitulo         0
Valor_CIF_USD    0
Peso_Neto_KG     0
dtype: int64

In [15]:
#Crear nuevas variables
#++++++++++++++++++++++

# Crear una columna llamada Ratio, que muestre el valor CIF de importación por kg. de mercadera importada
t3['Ratio_Dol/Kg']=t3['Valor_CIF_USD']/t3['Peso_Neto_KG']

t3

,año,aduana,cod_iso_pais,pais,cod_sección,seccion,cod_capitulo,capitulo,Valor_CIF_USD,Peso_Neto_KG,Ratio_Dol/Kg
0,2018,Rosario,BRA,Brasil,I,Animales Vivos Y Productos Del Reino Animal,2.0,Carne y despojos comestibles,293473928,1136096851,2.583177e-01
1,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,7.0,"Hortalizas, plantas, raíces y tubérculos alime...",8580,546,1.571429e+01
2,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,8.0,Frutas y frutos comestibles; cortezas de agrio...,9774392,11340,8.619393e+02
3,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,9.0,"Café, te, yerba y especias",2318503402,101202382,2.290957e+01
4,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,12.0,"Semillas y frutos oleaginosos, semillas y frut...",1528837,1,1.528837e+06
...,...,...,...,...,...,...,...,...,...,...,...
2708,2016,Rafaela,RP,Resto Países,XIII,"Manufacturas De Piedra, Yeso, Cemento, Ceramic...",70.0,Vidrio y sus manufacturas,1131,2,5.655000e+02
2709,2016,Rafaela,RP,Resto Países,XV,Metales Comunes Y Sus Manufacturas,73.0,"Manufacturas de fundición, hierro o acero",36831,9053,4.068375e+00
2710,2016,Rafaela,RP,Resto Países,XVI,"Maquinas, Aparatos Y Material Electrico; Sus P...",84.0,"Reactores nucleares, calderas, máquinas, apara...",985673,56274,1.751560e+01
2711,2016,Rafaela,RP,Resto Países,XVI,"Maquinas, Aparatos Y Material Electrico; Sus P...",85.0,"Máquinas, aparatos y material eléctrico y sus ...",48557,319,1.522163e+02
2712,2016,Rafaela,RP,Resto Países,XVIII,"Instrumentos De Optica, Medicina, Relojeria, M...",90.0,"Instrumentos y aparatos de óptica, de fotograf...",4313,3,1.437667e+03

In [16]:
# Indocadores estadísticos del valor CIF de importación
t3[['Valor_CIF_USD']].describe()

       Valor_CIF_USD
count   2.713000e+03
mean    8.041191e+07
std     4.989189e+08
min     2.000000e+00
25%     3.391200e+04
50%     3.343390e+05
75%     5.366608e+06
max     9.181242e+09

In [17]:
# Crear un rango de valores que exprese los niveles de importación como: Importante, medio, escazo" segun eliterio: sig. cr
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# Si el vol. de importación es menor al 1° cuartil entonces la categoria es : "Escazo".
# Si el vol. de importación es mayor o igual al 1° cuartil  y menor que el 2° cuartil  la categoria es : "Medio".
# Si el vol. de importación es mayor al 2° cuartil inclusive  la categoria es : "importante".

# Crear una variable categórica 'Nivel_Impo' cuyas categorias son: "Escazo", "Medio", "importante".
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

#  Las condiciones son:
# q1= cuantil 25%
# q2= cuantil 50%

# Calculo de cuantiles
Q1=t3['Valor_CIF_USD'].quantile(0.25)
Q2=t3['Valor_CIF_USD'].quantile(0.50)

# Crea columna vacia
t3['Nivel_Impo']=''

#establece condicionales para col. vacia

t3.loc[t3['Valor_CIF_USD']<Q1,'Nivel_Impo'] ='Escaso'
t3.loc[(t3['Valor_CIF_USD']>=Q1)&(t3['Valor_CIF_USD']<Q2),'Nivel_Impo'] ='Medio'
t3.loc[t3['Valor_CIF_USD']>=Q2,'Nivel_Impo'] ='Importante'

# print(Q1, Q2)
t3

,año,aduana,cod_iso_pais,pais,cod_sección,seccion,cod_capitulo,capitulo,Valor_CIF_USD,Peso_Neto_KG,Ratio_Dol/Kg,Nivel_Impo
0,2018,Rosario,BRA,Brasil,I,Animales Vivos Y Productos Del Reino Animal,2.0,Carne y despojos comestibles,293473928,1136096851,2.583177e-01,Importante
1,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,7.0,"Hortalizas, plantas, raíces y tubérculos alime...",8580,546,1.571429e+01,Escaso
2,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,8.0,Frutas y frutos comestibles; cortezas de agrio...,9774392,11340,8.619393e+02,Importante
3,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,9.0,"Café, te, yerba y especias",2318503402,101202382,2.290957e+01,Importante
4,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,12.0,"Semillas y frutos oleaginosos, semillas y frut...",1528837,1,1.528837e+06,Importante
...,...,...,...,...,...,...,...,...,...,...,...,...
2708,2016,Rafaela,RP,Resto Países,XIII,"Manufacturas De Piedra, Yeso, Cemento, Ceramic...",70.0,Vidrio y sus manufacturas,1131,2,5.655000e+02,Escaso
2709,2016,Rafaela,RP,Resto Países,XV,Metales Comunes Y Sus Manufacturas,73.0,"Manufacturas de fundición, hierro o acero",36831,9053,4.068375e+00,Medio
2710,2016,Rafaela,RP,Resto Países,XVI,"Maquinas, Aparatos Y Material Electrico; Sus P...",84.0,"Reactores nucleares, calderas, máquinas, apara...",985673,56274,1.751560e+01,Importante
2711,2016,Rafaela,RP,Resto Países,XVI,"Maquinas, Aparatos Y Material Electrico; Sus P...",85.0,"Máquinas, aparatos y material eléctrico y sus ...",48557,319,1.522163e+02,Medio
2712,2016,Rafaela,RP,Resto Países,XVIII,"Instrumentos De Optica, Medicina, Relojeria, M...",90.0,"Instrumentos y aparatos de óptica, de fotograf...",4313,3,1.437667e+03,Escaso

In [18]:
# Normalizar datos: Z-score, método min-max (forma manual)
#++++++++++++++++++++++++++++++++++++++++++

# Z-score=xi-mu(x)/sd(x)

# Min-Max=xi-min(x)/Max(x)-Min(x)

# Calcula valores normalizados (z-score) de las variables: "Valor CIF (en Dólares)" y "Peso Neto (en Kilos)"
mu_cf=t3['Valor_CIF_USD'].mean()
sd_cf=t3['Valor_CIF_USD'].std()

t3['Z_VCIF']=(t3['Valor_CIF_USD']-mu_cf)/sd_cf

mu_pn=t3['Peso_Neto_KG'].mean()
sd_pn=t3['Peso_Neto_KG'].std()
t3['Z_PN']=(t3['Peso_Neto_KG']-mu_pn)/sd_pn

t3

,año,aduana,cod_iso_pais,pais,cod_sección,seccion,cod_capitulo,capitulo,Valor_CIF_USD,Peso_Neto_KG,Ratio_Dol/Kg,Nivel_Impo,Z_VCIF,Z_PN
0,2018,Rosario,BRA,Brasil,I,Animales Vivos Y Productos Del Reino Animal,2.0,Carne y despojos comestibles,293473928,1136096851,2.583177e-01,Importante,0.427047,4.637056
1,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,7.0,"Hortalizas, plantas, raíces y tubérculos alime...",8580,546,1.571429e+01,Escaso,-0.161155,-0.101074
2,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,8.0,Frutas y frutos comestibles; cortezas de agrio...,9774392,11340,8.619393e+02,Importante,-0.141581,-0.101029
3,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,9.0,"Café, te, yerba y especias",2318503402,101202382,2.290957e+01,Importante,4.485882,0.320992
4,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,12.0,"Semillas y frutos oleaginosos, semillas y frut...",1528837,1,1.528837e+06,Importante,-0.158108,-0.101077
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2708,2016,Rafaela,RP,Resto Países,XIII,"Manufacturas De Piedra, Yeso, Cemento, Ceramic...",70.0,Vidrio y sus manufacturas,1131,2,5.655000e+02,Escaso,-0.161170,-0.101077
2709,2016,Rafaela,RP,Resto Países,XV,Metales Comunes Y Sus Manufacturas,73.0,"Manufacturas de fundición, hierro o acero",36831,9053,4.068375e+00,Medio,-0.161098,-0.101039
2710,2016,Rafaela,RP,Resto Países,XVI,"Maquinas, Aparatos Y Material Electrico; Sus P...",84.0,"Reactores nucleares, calderas, máquinas, apara...",985673,56274,1.751560e+01,Importante,-0.159197,-0.100842
2711,2016,Rafaela,RP,Resto Países,XVI,"Maquinas, Aparatos Y Material Electrico; Sus P...",85.0,"Máquinas, aparatos y material eléctrico y sus ...",48557,319,1.522163e+02,Medio,-0.161075,-0.101075
2712,2016,Rafaela,RP,Resto Países,XVIII,"Instrumentos De Optica, Medicina, Relojeria, M...",90.0,"Instrumentos y aparatos de óptica, de fotograf...",4313,3,1.437667e+03,Escaso,-0.161164,-0.101077

In [19]:
# Normalizar variables con  Standard Scaler / minmaxscaler # (forma automática)
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# StandardScaler is applied to each of the columns, where each value is subtracted with the mean of its column and divided by its standard deviation.
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler # xi-mu/sd

scaler=StandardScaler()
t3[['Z_auto_CIF','Z_auto_PN']]=scaler.fit_transform(t3[['Valor_CIF_USD','Peso_Neto_KG']])
t3

,año,aduana,cod_iso_pais,pais,cod_sección,seccion,cod_capitulo,capitulo,Valor_CIF_USD,Peso_Neto_KG,Ratio_Dol/Kg,Nivel_Impo,Z_VCIF,Z_PN,Z_auto_CIF,Z_auto_PN
0,2018,Rosario,BRA,Brasil,I,Animales Vivos Y Productos Del Reino Animal,2.0,Carne y despojos comestibles,293473928,1136096851,2.583177e-01,Importante,0.427047,4.637056,0.427126,4.637911
1,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,7.0,"Hortalizas, plantas, raíces y tubérculos alime...",8580,546,1.571429e+01,Escaso,-0.161155,-0.101074,-0.161185,-0.101093
2,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,8.0,Frutas y frutos comestibles; cortezas de agrio...,9774392,11340,8.619393e+02,Importante,-0.141581,-0.101029,-0.141607,-0.101048
3,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,9.0,"Café, te, yerba y especias",2318503402,101202382,2.290957e+01,Importante,4.485882,0.320992,4.486709,0.321051
4,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,12.0,"Semillas y frutos oleaginosos, semillas y frut...",1528837,1,1.528837e+06,Importante,-0.158108,-0.101077,-0.158137,-0.101095
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2708,2016,Rafaela,RP,Resto Países,XIII,"Manufacturas De Piedra, Yeso, Cemento, Ceramic...",70.0,Vidrio y sus manufacturas,1131,2,5.655000e+02,Escaso,-0.161170,-0.101077,-0.161200,-0.101095
2709,2016,Rafaela,RP,Resto Países,XV,Metales Comunes Y Sus Manufacturas,73.0,"Manufacturas de fundición, hierro o acero",36831,9053,4.068375e+00,Medio,-0.161098,-0.101039,-0.161128,-0.101058
2710,2016,Rafaela,RP,Resto Países,XVI,"Maquinas, Aparatos Y Material Electrico; Sus P...",84.0,"Reactores nucleares, calderas, máquinas, apara...",985673,56274,1.751560e+01,Importante,-0.159197,-0.100842,-0.159226,-0.100861
2711,2016,Rafaela,RP,Resto Países,XVI,"Maquinas, Aparatos Y Material Electrico; Sus P...",85.0,"Máquinas, aparatos y material eléctrico y sus ...",48557,319,1.522163e+02,Medio,-0.161075,-0.101075,-0.161105,-0.101094
2712,2016,Rafaela,RP,Resto Países,XVIII,"Instrumentos De Optica, Medicina, Relojeria, M...",90.0,"Instrumentos y aparatos de óptica, de fotograf...",4313,3,1.437667e+03,Escaso,-0.161164,-0.101077,-0.161193,-0.101095

In [20]:
scaler2=MinMaxScaler()
t3[['M_auto_CIF','M_auto_PN']]=scaler2.fit_transform(t3[['Valor_CIF_USD','Peso_Neto_KG']])
t3

,año,aduana,cod_iso_pais,pais,cod_sección,seccion,cod_capitulo,capitulo,Valor_CIF_USD,Peso_Neto_KG,Ratio_Dol/Kg,Nivel_Impo,Z_VCIF,Z_PN,Z_auto_CIF,Z_auto_PN,M_auto_CIF,M_auto_PN
0,2018,Rosario,BRA,Brasil,I,Animales Vivos Y Productos Del Reino Animal,2.0,Carne y despojos comestibles,293473928,1136096851,2.583177e-01,Importante,0.427047,4.637056,0.427126,4.637911,3.196451e-02,1.559183e-01
1,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,7.0,"Hortalizas, plantas, raíces y tubérculos alime...",8580,546,1.571429e+01,Escaso,-0.161155,-0.101074,-0.161185,-0.101093,9.342963e-07,7.493321e-08
2,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,8.0,Frutas y frutos comestibles; cortezas de agrio...,9774392,11340,8.619393e+02,Importante,-0.141581,-0.101029,-0.141607,-0.101048,1.064604e-03,1.556305e-06
3,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,9.0,"Café, te, yerba y especias",2318503402,101202382,2.290957e+01,Importante,4.485882,0.320992,4.486709,0.321051,2.525261e-01,1.388905e-02
4,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,12.0,"Semillas y frutos oleaginosos, semillas y frut...",1528837,1,1.528837e+06,Importante,-0.158108,-0.101077,-0.158137,-0.101095,1.665172e-04,1.372403e-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2708,2016,Rafaela,RP,Resto Países,XIII,"Manufacturas De Piedra, Yeso, Cemento, Ceramic...",70.0,Vidrio y sus manufacturas,1131,2,5.655000e+02,Escaso,-0.161170,-0.101077,-0.161200,-0.101095,1.229681e-07,2.744806e-10
2709,2016,Rafaela,RP,Resto Países,XV,Metales Comunes Y Sus Manufacturas,73.0,"Manufacturas de fundición, hierro o acero",36831,9053,4.068375e+00,Medio,-0.161098,-0.101039,-0.161128,-0.101058,4.011331e-06,1.242437e-06
2710,2016,Rafaela,RP,Resto Países,XVI,"Maquinas, Aparatos Y Material Electrico; Sus P...",84.0,"Reactores nucleares, calderas, máquinas, apara...",985673,56274,1.751560e+01,Importante,-0.159197,-0.100842,-0.159226,-0.100861,1.073570e-04,7.723061e-06
2711,2016,Rafaela,RP,Resto Países,XVI,"Maquinas, Aparatos Y Material Electrico; Sus P...",85.0,"Máquinas, aparatos y material eléctrico y sus ...",48557,319,1.522163e+02,Medio,-0.161075,-0.101075,-0.161105,-0.101094,5.288500e-06,4.377966e-08
2712,2016,Rafaela,RP,Resto Países,XVIII,"Instrumentos De Optica, Medicina, Relojeria, M...",90.0,"Instrumentos y aparatos de óptica, de fotograf...",4313,3,1.437667e+03,Escaso,-0.161164,-0.101077,-0.161193,-0.101095,4.695443e-07,4.117209e-10

In [21]:
# Normalizacion Decimal
#----------------------
# y_norm= X/10^j, siendo j: nro. digitos del nro. mas grande de un vector.
import numpy as np

xa = np.array([5.87506126, 5.80208926, 6.94279651, 7.52231974, 6.88083074])
y_norm = xa / 1e8

print(y_norm)

[5.87506126e-08 5.80208926e-08 6.94279651e-08 7.52231974e-08
 6.88083074e-08]

In [22]:
# Normalizacion logaritmica
#--------------------------
# X_norm=log10(X)

x=[750000,634000,8765900,33290456,7600300]
x_norm=np.log10(x)
x_norm

array([5.87506126, 5.80208926, 6.94279651, 7.52231974, 6.88083074])

In [23]:
# Repetir una fila de un data frame por ej. 3 veces
rep=[3 if val==8580 else 1 for val in t3['Valor_CIF_USD']]
t3=t3.loc[np.repeat(t3.index.values,rep)]
print(len(t3))

t3

2715

,año,aduana,cod_iso_pais,pais,cod_sección,seccion,cod_capitulo,capitulo,Valor_CIF_USD,Peso_Neto_KG,Ratio_Dol/Kg,Nivel_Impo,Z_VCIF,Z_PN,Z_auto_CIF,Z_auto_PN,M_auto_CIF,M_auto_PN
0,2018,Rosario,BRA,Brasil,I,Animales Vivos Y Productos Del Reino Animal,2.0,Carne y despojos comestibles,293473928,1136096851,0.258318,Importante,0.427047,4.637056,0.427126,4.637911,3.196451e-02,1.559183e-01
1,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,7.0,"Hortalizas, plantas, raíces y tubérculos alime...",8580,546,15.714286,Escaso,-0.161155,-0.101074,-0.161185,-0.101093,9.342963e-07,7.493321e-08
1,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,7.0,"Hortalizas, plantas, raíces y tubérculos alime...",8580,546,15.714286,Escaso,-0.161155,-0.101074,-0.161185,-0.101093,9.342963e-07,7.493321e-08
1,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,7.0,"Hortalizas, plantas, raíces y tubérculos alime...",8580,546,15.714286,Escaso,-0.161155,-0.101074,-0.161185,-0.101093,9.342963e-07,7.493321e-08
2,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,8.0,Frutas y frutos comestibles; cortezas de agrio...,9774392,11340,861.939330,Importante,-0.141581,-0.101029,-0.141607,-0.101048,1.064604e-03,1.556305e-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2708,2016,Rafaela,RP,Resto Países,XIII,"Manufacturas De Piedra, Yeso, Cemento, Ceramic...",70.0,Vidrio y sus manufacturas,1131,2,565.500000,Escaso,-0.161170,-0.101077,-0.161200,-0.101095,1.229681e-07,2.744806e-10
2709,2016,Rafaela,RP,Resto Países,XV,Metales Comunes Y Sus Manufacturas,73.0,"Manufacturas de fundición, hierro o acero",36831,9053,4.068375,Medio,-0.161098,-0.101039,-0.161128,-0.101058,4.011331e-06,1.242437e-06
2710,2016,Rafaela,RP,Resto Países,XVI,"Maquinas, Aparatos Y Material Electrico; Sus P...",84.0,"Reactores nucleares, calderas, máquinas, apara...",985673,56274,17.515602,Importante,-0.159197,-0.100842,-0.159226,-0.100861,1.073570e-04,7.723061e-06
2711,2016,Rafaela,RP,Resto Países,XVI,"Maquinas, Aparatos Y Material Electrico; Sus P...",85.0,"Máquinas, aparatos y material eléctrico y sus ...",48557,319,152.216301,Medio,-0.161075,-0.101075,-0.161105,-0.101094,5.288500e-06,4.377966e-08
2712,2016,Rafaela,RP,Resto Países,XVIII,"Instrumentos De Optica, Medicina, Relojeria, M...",90.0,"Instrumentos y aparatos de óptica, de fotograf...",4313,3,1437.666667,Escaso,-0.161164,-0.101077,-0.161193,-0.101095,4.695443e-07,4.117209e-10

In [24]:
# Modificar el valor de una celda de un df
#++++++++++++++++++++++++++++++++++++++++

# importante: las filas y columnas comienzan con la poscion 0,1,.......... El primer dato está en la posición "0"
# iloc "integer location": usa índices numéricos de posición para acceder a filas y columnas. 
#print(t2.iloc[1,0]) # muestra el dato de la 2da fila de la 1ra. columna.

t3.iloc[1,1]="rosaria" # toma la 2da.fila en la 2da.col.
t3.iloc[2,1]="ROsaRio" # toma la 3ra.fila en la 2da.col.
t3.iloc[3,1]="ROSARIO" # toma la 4ta.fila en la 2da.col.
t3.iloc[4,1]="RoSáRíO" # toma la 4ta.fila en la 2da.col.
t3

#"rosaria","ROsaRio","ROSARIO"

,año,aduana,cod_iso_pais,pais,cod_sección,seccion,cod_capitulo,capitulo,Valor_CIF_USD,Peso_Neto_KG,Ratio_Dol/Kg,Nivel_Impo,Z_VCIF,Z_PN,Z_auto_CIF,Z_auto_PN,M_auto_CIF,M_auto_PN
0,2018,Rosario,BRA,Brasil,I,Animales Vivos Y Productos Del Reino Animal,2.0,Carne y despojos comestibles,293473928,1136096851,0.258318,Importante,0.427047,4.637056,0.427126,4.637911,3.196451e-02,1.559183e-01
1,2018,rosaria,BRA,Brasil,II,Productos Del Reino Vegetal,7.0,"Hortalizas, plantas, raíces y tubérculos alime...",8580,546,15.714286,Escaso,-0.161155,-0.101074,-0.161185,-0.101093,9.342963e-07,7.493321e-08
1,2018,ROsaRio,BRA,Brasil,II,Productos Del Reino Vegetal,7.0,"Hortalizas, plantas, raíces y tubérculos alime...",8580,546,15.714286,Escaso,-0.161155,-0.101074,-0.161185,-0.101093,9.342963e-07,7.493321e-08
1,2018,ROSARIO,BRA,Brasil,II,Productos Del Reino Vegetal,7.0,"Hortalizas, plantas, raíces y tubérculos alime...",8580,546,15.714286,Escaso,-0.161155,-0.101074,-0.161185,-0.101093,9.342963e-07,7.493321e-08
2,2018,RoSáRíO,BRA,Brasil,II,Productos Del Reino Vegetal,8.0,Frutas y frutos comestibles; cortezas de agrio...,9774392,11340,861.939330,Importante,-0.141581,-0.101029,-0.141607,-0.101048,1.064604e-03,1.556305e-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2708,2016,Rafaela,RP,Resto Países,XIII,"Manufacturas De Piedra, Yeso, Cemento, Ceramic...",70.0,Vidrio y sus manufacturas,1131,2,565.500000,Escaso,-0.161170,-0.101077,-0.161200,-0.101095,1.229681e-07,2.744806e-10
2709,2016,Rafaela,RP,Resto Países,XV,Metales Comunes Y Sus Manufacturas,73.0,"Manufacturas de fundición, hierro o acero",36831,9053,4.068375,Medio,-0.161098,-0.101039,-0.161128,-0.101058,4.011331e-06,1.242437e-06
2710,2016,Rafaela,RP,Resto Países,XVI,"Maquinas, Aparatos Y Material Electrico; Sus P...",84.0,"Reactores nucleares, calderas, máquinas, apara...",985673,56274,17.515602,Importante,-0.159197,-0.100842,-0.159226,-0.100861,1.073570e-04,7.723061e-06
2711,2016,Rafaela,RP,Resto Países,XVI,"Maquinas, Aparatos Y Material Electrico; Sus P...",85.0,"Máquinas, aparatos y material eléctrico y sus ...",48557,319,152.216301,Medio,-0.161075,-0.101075,-0.161105,-0.101094,5.288500e-06,4.377966e-08
2712,2016,Rafaela,RP,Resto Países,XVIII,"Instrumentos De Optica, Medicina, Relojeria, M...",90.0,"Instrumentos y aparatos de óptica, de fotograf...",4313,3,1437.666667,Escaso,-0.161164,-0.101077,-0.161193,-0.101095,4.695443e-07,4.117209e-10

In [25]:
#  Normalizar cadenas de caracteres mediante expresiones regulares REGEX 
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# Reemplazar cadena de caracter  ### VER REGEX Regular Expression#
# Reemplaza variantes de "Rosario" (con o sin acentos) por "Rosario"
t3['aduana'] = t3['aduana'].str.replace(r'(?i)ros[a-záéíóúñ]{1,6}', 'Rosario', regex=True)

t3

# r': indica que es una cadena cruda  de caracteres (raw string).
# Los caracteres de escape: como \n ( salto de linea) o \t (espacio tabulador) no se interpretan.

#(?i):() Busca caract. ignorando los casps de mayúsculas/minúsculas).
# El patrón "ros" busca toodos los carac. que comiencen con "ros".
#[a-záéíóúñ]{1,6} busca de 1 a 6 caract. (incluye acentos y ñ).

# regex = True: Especifica que el primer argumento es una expresión regular, en este caso: r"(?i)ro[A-Z,a-z]{1,8}"
# case = False: La búsqueda no diferencia entre mayúsculas y minúsculas.

,año,aduana,cod_iso_pais,pais,cod_sección,seccion,cod_capitulo,capitulo,Valor_CIF_USD,Peso_Neto_KG,Ratio_Dol/Kg,Nivel_Impo,Z_VCIF,Z_PN,Z_auto_CIF,Z_auto_PN,M_auto_CIF,M_auto_PN
0,2018,Rosario,BRA,Brasil,I,Animales Vivos Y Productos Del Reino Animal,2.0,Carne y despojos comestibles,293473928,1136096851,0.258318,Importante,0.427047,4.637056,0.427126,4.637911,3.196451e-02,1.559183e-01
1,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,7.0,"Hortalizas, plantas, raíces y tubérculos alime...",8580,546,15.714286,Escaso,-0.161155,-0.101074,-0.161185,-0.101093,9.342963e-07,7.493321e-08
1,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,7.0,"Hortalizas, plantas, raíces y tubérculos alime...",8580,546,15.714286,Escaso,-0.161155,-0.101074,-0.161185,-0.101093,9.342963e-07,7.493321e-08
1,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,7.0,"Hortalizas, plantas, raíces y tubérculos alime...",8580,546,15.714286,Escaso,-0.161155,-0.101074,-0.161185,-0.101093,9.342963e-07,7.493321e-08
2,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,8.0,Frutas y frutos comestibles; cortezas de agrio...,9774392,11340,861.939330,Importante,-0.141581,-0.101029,-0.141607,-0.101048,1.064604e-03,1.556305e-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2708,2016,Rafaela,RP,Resto Países,XIII,"Manufacturas De Piedra, Yeso, Cemento, Ceramic...",70.0,Vidrio y sus manufacturas,1131,2,565.500000,Escaso,-0.161170,-0.101077,-0.161200,-0.101095,1.229681e-07,2.744806e-10
2709,2016,Rafaela,RP,Resto Países,XV,Metales Comunes Y Sus Manufacturas,73.0,"Manufacturas de fundición, hierro o acero",36831,9053,4.068375,Medio,-0.161098,-0.101039,-0.161128,-0.101058,4.011331e-06,1.242437e-06
2710,2016,Rafaela,RP,Resto Países,XVI,"Maquinas, Aparatos Y Material Electrico; Sus P...",84.0,"Reactores nucleares, calderas, máquinas, apara...",985673,56274,17.515602,Importante,-0.159197,-0.100842,-0.159226,-0.100861,1.073570e-04,7.723061e-06
2711,2016,Rafaela,RP,Resto Países,XVI,"Maquinas, Aparatos Y Material Electrico; Sus P...",85.0,"Máquinas, aparatos y material eléctrico y sus ...",48557,319,152.216301,Medio,-0.161075,-0.101075,-0.161105,-0.101094,5.288500e-06,4.377966e-08
2712,2016,Rafaela,RP,Resto Países,XVIII,"Instrumentos De Optica, Medicina, Relojeria, M...",90.0,"Instrumentos y aparatos de óptica, de fotograf...",4313,3,1437.666667,Escaso,-0.161164,-0.101077,-0.161193,-0.101095,4.695443e-07,4.117209e-10

In [26]:
# Modificar celdas del atributo "Pais"

t3.iloc[1,3]="BRASIL" # toma la 2da.fila en la 4ta.col.
t3.iloc[2,3]="BRAZIL" # toma la 3ra.fila en la 4ta.col.
t3.iloc[3,3]="BRAzil" # toma la 4ta.fila en la 4ta.col.
t3.iloc[4,3]="bRásil" # toma la 4ta.fila en la 4ta.col.
t3

,año,aduana,cod_iso_pais,pais,cod_sección,seccion,cod_capitulo,capitulo,Valor_CIF_USD,Peso_Neto_KG,Ratio_Dol/Kg,Nivel_Impo,Z_VCIF,Z_PN,Z_auto_CIF,Z_auto_PN,M_auto_CIF,M_auto_PN
0,2018,Rosario,BRA,Brasil,I,Animales Vivos Y Productos Del Reino Animal,2.0,Carne y despojos comestibles,293473928,1136096851,0.258318,Importante,0.427047,4.637056,0.427126,4.637911,3.196451e-02,1.559183e-01
1,2018,Rosario,BRA,BRASIL,II,Productos Del Reino Vegetal,7.0,"Hortalizas, plantas, raíces y tubérculos alime...",8580,546,15.714286,Escaso,-0.161155,-0.101074,-0.161185,-0.101093,9.342963e-07,7.493321e-08
1,2018,Rosario,BRA,BRAZIL,II,Productos Del Reino Vegetal,7.0,"Hortalizas, plantas, raíces y tubérculos alime...",8580,546,15.714286,Escaso,-0.161155,-0.101074,-0.161185,-0.101093,9.342963e-07,7.493321e-08
1,2018,Rosario,BRA,BRAzil,II,Productos Del Reino Vegetal,7.0,"Hortalizas, plantas, raíces y tubérculos alime...",8580,546,15.714286,Escaso,-0.161155,-0.101074,-0.161185,-0.101093,9.342963e-07,7.493321e-08
2,2018,Rosario,BRA,bRásil,II,Productos Del Reino Vegetal,8.0,Frutas y frutos comestibles; cortezas de agrio...,9774392,11340,861.939330,Importante,-0.141581,-0.101029,-0.141607,-0.101048,1.064604e-03,1.556305e-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2708,2016,Rafaela,RP,Resto Países,XIII,"Manufacturas De Piedra, Yeso, Cemento, Ceramic...",70.0,Vidrio y sus manufacturas,1131,2,565.500000,Escaso,-0.161170,-0.101077,-0.161200,-0.101095,1.229681e-07,2.744806e-10
2709,2016,Rafaela,RP,Resto Países,XV,Metales Comunes Y Sus Manufacturas,73.0,"Manufacturas de fundición, hierro o acero",36831,9053,4.068375,Medio,-0.161098,-0.101039,-0.161128,-0.101058,4.011331e-06,1.242437e-06
2710,2016,Rafaela,RP,Resto Países,XVI,"Maquinas, Aparatos Y Material Electrico; Sus P...",84.0,"Reactores nucleares, calderas, máquinas, apara...",985673,56274,17.515602,Importante,-0.159197,-0.100842,-0.159226,-0.100861,1.073570e-04,7.723061e-06
2711,2016,Rafaela,RP,Resto Países,XVI,"Maquinas, Aparatos Y Material Electrico; Sus P...",85.0,"Máquinas, aparatos y material eléctrico y sus ...",48557,319,152.216301,Medio,-0.161075,-0.101075,-0.161105,-0.101094,5.288500e-06,4.377966e-08
2712,2016,Rafaela,RP,Resto Países,XVIII,"Instrumentos De Optica, Medicina, Relojeria, M...",90.0,"Instrumentos y aparatos de óptica, de fotograf...",4313,3,1437.666667,Escaso,-0.161164,-0.101077,-0.161193,-0.101095,4.695443e-07,4.117209e-10

In [27]:
# Normalizar la cadena de carac. "Brasil" mediante expresiones regulares REGEX
t3['pais']=t3['pais'].str.replace(r'(?i)br[a-záéíóúñ]{1,6}', 'Brasil', regex=True)
t3

,año,aduana,cod_iso_pais,pais,cod_sección,seccion,cod_capitulo,capitulo,Valor_CIF_USD,Peso_Neto_KG,Ratio_Dol/Kg,Nivel_Impo,Z_VCIF,Z_PN,Z_auto_CIF,Z_auto_PN,M_auto_CIF,M_auto_PN
0,2018,Rosario,BRA,Brasil,I,Animales Vivos Y Productos Del Reino Animal,2.0,Carne y despojos comestibles,293473928,1136096851,0.258318,Importante,0.427047,4.637056,0.427126,4.637911,3.196451e-02,1.559183e-01
1,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,7.0,"Hortalizas, plantas, raíces y tubérculos alime...",8580,546,15.714286,Escaso,-0.161155,-0.101074,-0.161185,-0.101093,9.342963e-07,7.493321e-08
1,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,7.0,"Hortalizas, plantas, raíces y tubérculos alime...",8580,546,15.714286,Escaso,-0.161155,-0.101074,-0.161185,-0.101093,9.342963e-07,7.493321e-08
1,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,7.0,"Hortalizas, plantas, raíces y tubérculos alime...",8580,546,15.714286,Escaso,-0.161155,-0.101074,-0.161185,-0.101093,9.342963e-07,7.493321e-08
2,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,8.0,Frutas y frutos comestibles; cortezas de agrio...,9774392,11340,861.939330,Importante,-0.141581,-0.101029,-0.141607,-0.101048,1.064604e-03,1.556305e-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2708,2016,Rafaela,RP,Resto Países,XIII,"Manufacturas De Piedra, Yeso, Cemento, Ceramic...",70.0,Vidrio y sus manufacturas,1131,2,565.500000,Escaso,-0.161170,-0.101077,-0.161200,-0.101095,1.229681e-07,2.744806e-10
2709,2016,Rafaela,RP,Resto Países,XV,Metales Comunes Y Sus Manufacturas,73.0,"Manufacturas de fundición, hierro o acero",36831,9053,4.068375,Medio,-0.161098,-0.101039,-0.161128,-0.101058,4.011331e-06,1.242437e-06
2710,2016,Rafaela,RP,Resto Países,XVI,"Maquinas, Aparatos Y Material Electrico; Sus P...",84.0,"Reactores nucleares, calderas, máquinas, apara...",985673,56274,17.515602,Importante,-0.159197,-0.100842,-0.159226,-0.100861,1.073570e-04,7.723061e-06
2711,2016,Rafaela,RP,Resto Países,XVI,"Maquinas, Aparatos Y Material Electrico; Sus P...",85.0,"Máquinas, aparatos y material eléctrico y sus ...",48557,319,152.216301,Medio,-0.161075,-0.101075,-0.161105,-0.101094,5.288500e-06,4.377966e-08
2712,2016,Rafaela,RP,Resto Países,XVIII,"Instrumentos De Optica, Medicina, Relojeria, M...",90.0,"Instrumentos y aparatos de óptica, de fotograf...",4313,3,1437.666667,Escaso,-0.161164,-0.101077,-0.161193,-0.101095,4.695443e-07,4.117209e-10

In [28]:

# Crear datos vacios y NAN
#+++++++++++++++++++++++++++

# Reemplazar datos. El parametro de la f. replace es un diccionario {key:value,key:value}, inplace:True, reemplaza el dato en el Df original
t3['Valor_CIF_USD'].replace({8580:np.nan},inplace=True)
t3['Peso_Neto_KG'].replace({5.460000e+02:np.nan},inplace=True)
t3

,año,aduana,cod_iso_pais,pais,cod_sección,seccion,cod_capitulo,capitulo,Valor_CIF_USD,Peso_Neto_KG,Ratio_Dol/Kg,Nivel_Impo,Z_VCIF,Z_PN,Z_auto_CIF,Z_auto_PN,M_auto_CIF,M_auto_PN
0,2018,Rosario,BRA,Brasil,I,Animales Vivos Y Productos Del Reino Animal,2.0,Carne y despojos comestibles,293473928.0,1.136097e+09,0.258318,Importante,0.427047,4.637056,0.427126,4.637911,3.196451e-02,1.559183e-01
1,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,7.0,"Hortalizas, plantas, raíces y tubérculos alime...",NaN,NaN,15.714286,Escaso,-0.161155,-0.101074,-0.161185,-0.101093,9.342963e-07,7.493321e-08
1,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,7.0,"Hortalizas, plantas, raíces y tubérculos alime...",NaN,NaN,15.714286,Escaso,-0.161155,-0.101074,-0.161185,-0.101093,9.342963e-07,7.493321e-08
1,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,7.0,"Hortalizas, plantas, raíces y tubérculos alime...",NaN,NaN,15.714286,Escaso,-0.161155,-0.101074,-0.161185,-0.101093,9.342963e-07,7.493321e-08
2,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,8.0,Frutas y frutos comestibles; cortezas de agrio...,9774392.0,1.134000e+04,861.939330,Importante,-0.141581,-0.101029,-0.141607,-0.101048,1.064604e-03,1.556305e-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2708,2016,Rafaela,RP,Resto Países,XIII,"Manufacturas De Piedra, Yeso, Cemento, Ceramic...",70.0,Vidrio y sus manufacturas,1131.0,2.000000e+00,565.500000,Escaso,-0.161170,-0.101077,-0.161200,-0.101095,1.229681e-07,2.744806e-10
2709,2016,Rafaela,RP,Resto Países,XV,Metales Comunes Y Sus Manufacturas,73.0,"Manufacturas de fundición, hierro o acero",36831.0,9.053000e+03,4.068375,Medio,-0.161098,-0.101039,-0.161128,-0.101058,4.011331e-06,1.242437e-06
2710,2016,Rafaela,RP,Resto Países,XVI,"Maquinas, Aparatos Y Material Electrico; Sus P...",84.0,"Reactores nucleares, calderas, máquinas, apara...",985673.0,5.627400e+04,17.515602,Importante,-0.159197,-0.100842,-0.159226,-0.100861,1.073570e-04,7.723061e-06
2711,2016,Rafaela,RP,Resto Países,XVI,"Maquinas, Aparatos Y Material Electrico; Sus P...",85.0,"Máquinas, aparatos y material eléctrico y sus ...",48557.0,3.190000e+02,152.216301,Medio,-0.161075,-0.101075,-0.161105,-0.101094,5.288500e-06,4.377966e-08
2712,2016,Rafaela,RP,Resto Países,XVIII,"Instrumentos De Optica, Medicina, Relojeria, M...",90.0,"Instrumentos y aparatos de óptica, de fotograf...",4313.0,3.000000e+00,1437.666667,Escaso,-0.161164,-0.101077,-0.161193,-0.101095,4.695443e-07,4.117209e-10

In [ ]:
# Reemplazar datos nulos y vacios por la media o por  la moda
#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

# Simple imputer se usa para completar los valores faltantes (NaN) en un conjunto de datos.
# Puede usar indicadores estadísticos (mean,median, mode) o un valor constante para reemplazar los valores faltantes.


from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='median') #np.nan
t3[['Valor_CIF_USD','Peso_Neto_KG']]=imp.fit_transform(t3[['Valor_CIF_USD','Peso_Neto_KG']])
t3

,año,aduana,cod_iso_pais,pais,cod_sección,seccion,cod_capitulo,capitulo,Valor_CIF_USD,Peso_Neto_KG,Ratio_Dol/Kg,Nivel_Impo,Z_VCIF,Z_PN,Z_auto_CIF,Z_auto_PN,M_auto_CIF,M_auto_PN
0,2018,Rosario,BRA,Brasil,I,Animales Vivos Y Productos Del Reino Animal,2.0,Carne y despojos comestibles,293473928.0,1.136097e+09,0.258318,Importante,0.427047,4.637056,0.427126,4.637911,3.196451e-02,1.559183e-01
1,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,7.0,"Hortalizas, plantas, raíces y tubérculos alime...",334606.5,3.154700e+04,15.714286,Escaso,-0.161155,-0.101074,-0.161185,-0.101093,9.342963e-07,7.493321e-08
1,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,7.0,"Hortalizas, plantas, raíces y tubérculos alime...",334606.5,3.154700e+04,15.714286,Escaso,-0.161155,-0.101074,-0.161185,-0.101093,9.342963e-07,7.493321e-08
1,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,7.0,"Hortalizas, plantas, raíces y tubérculos alime...",334606.5,3.154700e+04,15.714286,Escaso,-0.161155,-0.101074,-0.161185,-0.101093,9.342963e-07,7.493321e-08
2,2018,Rosario,BRA,Brasil,II,Productos Del Reino Vegetal,8.0,Frutas y frutos comestibles; cortezas de agrio...,9774392.0,1.134000e+04,861.939330,Importante,-0.141581,-0.101029,-0.141607,-0.101048,1.064604e-03,1.556305e-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2708,2016,Rafaela,RP,Resto Países,XIII,"Manufacturas De Piedra, Yeso, Cemento, Ceramic...",70.0,Vidrio y sus manufacturas,1131.0,2.000000e+00,565.500000,Escaso,-0.161170,-0.101077,-0.161200,-0.101095,1.229681e-07,2.744806e-10
2709,2016,Rafaela,RP,Resto Países,XV,Metales Comunes Y Sus Manufacturas,73.0,"Manufacturas de fundición, hierro o acero",36831.0,9.053000e+03,4.068375,Medio,-0.161098,-0.101039,-0.161128,-0.101058,4.011331e-06,1.242437e-06
2710,2016,Rafaela,RP,Resto Países,XVI,"Maquinas, Aparatos Y Material Electrico; Sus P...",84.0,"Reactores nucleares, calderas, máquinas, apara...",985673.0,5.627400e+04,17.515602,Importante,-0.159197,-0.100842,-0.159226,-0.100861,1.073570e-04,7.723061e-06
2711,2016,Rafaela,RP,Resto Países,XVI,"Maquinas, Aparatos Y Material Electrico; Sus P...",85.0,"Máquinas, aparatos y material eléctrico y sus ...",48557.0,3.190000e+02,152.216301,Medio,-0.161075,-0.101075,-0.161105,-0.101094,5.288500e-06,4.377966e-08
2712,2016,Rafaela,RP,Resto Países,XVIII,"Instrumentos De Optica, Medicina, Relojeria, M...",90.0,"Instrumentos y aparatos de óptica, de fotograf...",4313.0,3.000000e+00,1437.666667,Escaso,-0.161164,-0.101077,-0.161193,-0.101095,4.695443e-07,4.117209e-10